[package]
name = "actix-web"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
twa-jwks = { path = "../../twa-jwks", version = "1.1.0", features = ["actix-web"] }
actix-web = { version = "4.3", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
